### PR TITLE
fix: Prevent query dropdown menus from overlaping

### LINKED ISSUE #2254: Intertwined dropdowns
# Bug

**Describe the bug**
In the query panel, the "settings" and "download" dropdowns behave as on/off toggles, which causes them to overlap each other in some cases and brings undesirable UX.

**To Reproduce**
1. Add some queryable layer to map
2. Click on some feature
3. In query panel, open the "settings/gears" option
4. In query panel, open the "download" option
5. In query panel, open the "settings/gears" option

**Expected behavior**
Opening one dropdown shall close the other. Otherwise they overlap.

**Screenshots**
image
image
image
image
image

**Additional context**
Cosmetic bug

### PR DESCRIPTION
**Pull request by FilipLeitner**
## Related issues or pull requests
fixes #2254 

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Dependency updates
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe)
- [ ] I am unsure (we'll look into it together)

## Do you introduce a breaking change?

- [ ] Yes
- [x] No
- [ ] I am unsure (no worries, we'll find out)

## Checklist

- [ ] I understand and agree that the changes in this PR will be licensed under the [MIT License]
- [ ] I have followed the [guidelines for contributing](https://github.com/hslayers/hslayers-ng/blob/master/CONTRIBUTING.md)
- [ ] The proposed change fits to the content of the [code of conduct](https://github.com/hslayers/hslayers-ng/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have added or updated tests and documentation, and the test suite passes (run `npm test` locally)
- [ ] I'm lost; why do I have to check so many boxes? Please help!

### CODE REVIEW

**Review by raitisbe — APPROVED** [review]

File: projects/hslayers/src/components/query/feature-list.component.ts [hunk 1]
```diff
@@ -50,24 +50,34 @@ export class HsQueryFeatureListComponent {
...
-  }
-
   olFeatureArray(): Feature<Geometry>[] {
     return this.features.map((feature) => feature.feature);
   }
 
+  /**
+   * Toggle dropdown menus
+   * @param beingToggled Menu being toggled
+   * @param other Other menu to be clsoed if opened
```
Comment (jmacura) [inline projects/hslayers/src/components/query/feature-list.component.ts:60]:
```suggestion
   * @param other Other menu to be closed if opened
```

File: projects/hslayers/src/components/query/feature.component.ts [hunk 2]
```diff
@@ -99,12 +99,22 @@ export class HsQueryFeatureComponent implements AfterViewInit {
     this.HsMapService.fitExtent(extent);
   }
 
+  /**
+   * Toggle dropdown menus
+   * @param beingToggled Menu being toggled
+   * @param other Other menu to be clsoed if opened
```
Comment (jmacura) [inline projects/hslayers/src/components/query/feature.component.ts:105]:
```suggestion
   * @param other Other menu to be closed if opened
```
